# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mi asombroooooso titulo
email: degixcala@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este es mi Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: danicg3
github_username:  dancg

# Build settings
markdown: kramdown
